const images = {
    logo: require('~/assets/images/iconHeader/logo.svg').default,
    optionsIcon: require('~/assets/images/iconHeader/optionsIcon.svg').default,
    bellIcon: require('~/assets/images/iconHeader/bellIcon.svg').default,
    inboxIcon: require('~/assets/images/iconHeader/inboxIcon.svg').default,
    userPlusIcon: require('~/assets/images/iconHeader/userPlusIcon.svg').default,
    insertIcon: require('~/assets/images/iconHeader/insertIcon.svg').default,
    searchIcon: require('~/assets/images/iconHeader/searchIcon.svg').default,
    questionIcon: require('~/assets/images/iconHeader/questionIcon.svg').default,
    homeIcon: require('~/assets/images/iconBody/homeIcon.svg').default,
    taskIcon: require('~/assets/images/iconBody/taskIcon.svg').default,
    arrowDownIcon: require('~/assets/images/iconBody/arrowDownIcon.svg').default,
    arrowLeftIcon: require('~/assets/images/iconBody/arrowLeftIcon.svg').default,
    arrowRightIcon: require('~/assets/images/iconBody/arrowRightIcon.svg').default,
    arrowUpIcon: require('~/assets/images/iconBody/arrowUpIcon.svg').default,
    filterIcon: require('~/assets/images/iconBody/filterIcon.svg').default,
    favouriteIcon: require('~/assets/images/iconBody/favouriteIcon.svg').default,
    homeSolidIcon: require('~/assets/images/iconBody/homeSolidIcon.svg').default,
    plusIcon: require('~/assets/images/iconBody/plusIcon.svg').default,
    threeDotsIcon: require('~/assets/images/iconBody/threeDotsIcon.svg').default,
    publicBoardIcon: require('~/assets/images/iconBody/publicBoardIcon.svg').default,
    clockIcon: require('~/assets/images/iconBody/clockIcon.svg').default,
    moreInfoIcon: require('~/assets/images/iconBody/moreInfoIcon.svg').default,
    personIcon: require('~/assets/images/iconBody/personIcon.svg').default,
    sortIcon: require('~/assets/images/iconBody/sortIcon.svg').default,
    hideIcon: require('~/assets/images/iconBody/hideIcon.svg').default,
    searchOptions: require('~/assets/images/iconBody/searchOptions.svg').default,
};
export default images;
